# Utilizar una imagen base de Python
FROM python:3.12-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de requisitos y el código
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

# Exponer el puerto (5000 por ejemplo)
EXPOSE 5000

# Comando para correr la aplicación
CMD ["python", "app.py"]
